version: '3'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: login-service
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: 'rabbitmq:3.8-management-alpine'
    container_name: 'rabbitmq-nodejs'
    hostname: "rabbitmq"
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASSWORD=admin"
    ports:
      - 15672:15672
      - 5672:5672
#     networks:
#       - rabbitmq_go_net

# networks:
#   rabbitmq_go_net:
#     driver: bridge